### ISSUE TITLE
Open-source opportunities for women in astronomy

### ISSUE THREAD

**Issue by kakirastern** [facebook-developer-circle-delhi/Meetup-Resources#81]
**Talk Title:** Open-source opportunities for women in astronomy
**Talk Description:** The talk will be on opportunities for women in open-source software development for astronomy. The speaker will do a brief introduction of the Astropy and SunPy projects, of which she is an active member. Also, some introduction of the Outreachy internship program will be given. 
**Talk Duration:** 15 to 20 minutes
**Type of Talk:** Session
**Prerequisites for talk:** (if any) N/A
**Link to slides:** (Will be provided at least 2 days before the talk)
**About yourself:** (Include links to previous talks if you have given any) https://github.com/kakirastern
**Month(s) available to speak:** October 2020

@festusdrakon

**Comment by harshitjuneja** [comment]
Thanks for the details Kris. Can you also attach one of your photos to be featured in the event poster?

**Comment by kakirastern** [comment]
Sure! Here it is...

![image](https://user-images.githubusercontent.com/26264600/94948743-665f3d80-0512-11eb-9cf6-48683a0559fb.png)

**Comment by harshitjuneja** [comment]
Great. Your talk is confirmed for 10th of October 4pm IST. 

@festusdrakon will keep in touch. Thanks!

Closing the issue.

**Comment by kakirastern** [comment]
Thanks @harshitjuneja Appreciate it!
